### ISSUE TITLE
Cannot download preprocessed dataset

### ISSUE THREAD

**Issue by ejko99** [luo-group/PenLight#3]
Hi, thank you for your great work!

I am highly interested in your work, and am trying to develop on your work.

However, I cannot download preprocessed dataset because it is an empty folder.

Below is a link you put in your README file.

Thanks in advance.

`Complete preprocessed datasets can be found [here](https://drive.google.com/drive/folders/1k7uqPbsI6ZROcZYA_shmebXEnHh-q8dV?usp=sharing).`

**Comment by luojq19** [comment]
Hi, sorry for the inconvenience! The former data file was accidentally lost. We have updated a new version of code with the same datasets, please refer to the new `main` branch for details. The original version was moved to the `original` branch. Thanks for your interest, please get in touch with me if there's any issue with the code or paper.

**Comment by ejko99** [comment]
I will check the `main` brunch.
Thanks!
