### ISSUE TITLE
EC number prediction using protein sequences

### ISSUE THREAD

**Issue by dsaeedeh** [luo-group/PenLight#4]
Thank you for your interesting work! 

My dataset is a .fasta file of protein sequences with no 3d structure information for them. How can I use your model to predict ec numbers for my protein sequences?

Another question I have is how I can create the dataset for the model with the format you used for model training. I have .pdb files of proteins.

**Comment by luojq19** [comment]
For protein sequences with no 3D structure, I recommend using AlphaFold2 to generate corresponding structures in order to use PenLight model.
For data processing, you can use PDBParser in Biopython package to extract the atom coordinates from pdb files.
